const ACCESS_PERMISSIONS = [
  'USER_READ',
  'USER_CREATE',
  'USER_UPDATE',
  'USER_DELETE',

  'ACCESS_PERMISSION_READ',
  'ACCESS_PERMISSION_CREATE',
  'ACCESS_PERMISSION_UPDATE',
  'ACCESS_PERMISSION_DELETE',
];

enum PermissionEnum {
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  ACCESS_PERMISSION_READ = 'ACCESS_PERMISSION_READ',
  ACCESS_PERMISSION_CREATE = 'ACCESS_PERMISSION_CREATE',
  ACCESS_PERMISSION_UPDATE = 'ACCESS_PERMISSION_UPDATE',
  ACCESS_PERMISSION_DELETE = 'ACCESS_PERMISSION_DELETE',
}

export {ACCESS_PERMISSIONS, PermissionEnum}