const ACCESS_PERMISSIONS = [
  'USER_READ',
  'USER_CREATE',
  'USER_UPDATE',
  'USER_DELETE',

  'ACCESS_PERMISSION_READ',
  'ACCESS_PERMISSION_CREATE',
  'ACCESS_PERMISSION_UPDATE',
  'ACCESS_PERMISSION_DELETE',

  'WORK_SPACE_READ',
  'WORK_SPACE_CREATE',
  'WORK_SPACE_UPDATE',
  'WORK_SPACE_DELETE',

  'PROJECT_READ',
  'PROJECT_CREATE',
  'PROJECT_UPDATE',
  'PROJECT_DELETE',
];

enum PermissionEnum {
  NO_PERMISSION = 'NO_PERMISSION',

  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  ACCESS_PERMISSION_READ = 'ACCESS_PERMISSION_READ',
  ACCESS_PERMISSION_CREATE = 'ACCESS_PERMISSION_CREATE',
  ACCESS_PERMISSION_UPDATE = 'ACCESS_PERMISSION_UPDATE',
  ACCESS_PERMISSION_DELETE = 'ACCESS_PERMISSION_DELETE',

  WORK_SPACE_READ = 'WORK_SPACE_READ',
  WORK_SPACE_CREATE = 'WORK_SPACE_CREATE',
  WORK_SPACE_UPDATE = 'WORK_SPACE_UPDATE',
  WORK_SPACE_DELETE = 'WORK_SPACE_DELETE',

  PROJECT_READ = 'PROJECT_READ',
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_DELETE = 'PROJECT_DELETE',
}

export { ACCESS_PERMISSIONS, PermissionEnum };
